// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.{environment}.vrtp-sms.example.net/v1' | (string & {});
};

export type Error = {
    code?: string;
    message?: string;
    details?: {
        [key: string]: unknown;
    };
};

/**
 * Reference to an ontology concept (03-postgresql-schema.sql ontology.concepts)
 */
export type ConceptRef = {
    concept_id?: string;
    /**
     * Read-only, resolved server-side
     */
    pref_label?: string;
};

export type Park = {
    id?: string;
    name?: string;
};

export type Person = {
    id?: string;
    name?: string;
    role_title?: string;
    email?: string;
};

export type PersonInput = {
    name: string;
    role_title?: string;
    email?: string;
};

export type Asset = AssetInput & {
    id?: string;
    created_at?: string;
    updated_at?: string;
};

export type AssetInput = {
    name: string;
    park_id?: string;
    asset_type?: ConceptRef;
    /**
     * TO BE CONFIRMED — see PLATFORM_ARCHITECTURE_V2.md §5
     */
    iso55000_class?: string;
    status?: string;
};

export type Hazard = HazardInput & {
    id?: string;
    created_at?: string;
    updated_at?: string;
};

export type HazardInput = {
    asset_id?: string;
    name: string;
    description: string;
    exposure_pathway?: string;
    possible_consequence?: string;
    category?: ConceptRef;
    energy_source?: ConceptRef;
    date_identified?: string;
    owner_person_id?: string;
    /**
     * Amusement device hazard — 11-safety-case-demonstration-model.md §3
     */
    is_adh?: boolean;
    device_boundary_id?: string;
};

export type Risk = RiskInput & {
    id?: string;
    /**
     * Derived — 07-inference-rules-catalogue.md R1
     */
    readonly inherent_rating?: 'Extreme' | 'High' | 'Medium' | 'Low';
    readonly current_rating?: 'Extreme' | 'High' | 'Medium' | 'Low';
};

export type RiskInput = {
    hazard_id: string;
    description: string;
    cause?: string;
    inherent_likelihood?: number;
    inherent_consequence?: number;
    current_likelihood?: number;
    current_consequence?: number;
    target_likelihood?: number;
    target_consequence?: number;
    /**
     * General WHS duty justification. For ADI/Chapter-9A-scoped risks, use serious_risk_justification and SFAIRP terminology in any generated Demonstration text — 09-regulatory-knowledge-model.md §3
     */
    sfarp_justification?: string;
    status?: 'Open' | 'Under Review' | 'Closed';
    review_date?: string;
    /**
     * Chapter 9A serious risk classification (WHS Reg s.608B(1)(b)) — operator-defined threshold, see 09-regulatory-knowledge-model.md §6
     */
    is_serious_risk?: boolean;
    serious_risk_justification?: string;
};

export type Control = ControlInput & {
    id?: string;
    readonly classification?: 'Control' | 'Support' | 'Verification';
    readonly is_critical?: boolean;
};

export type ControlInput = {
    risk_id: string;
    description: string;
    control_type: 'Prevention' | 'Mitigation';
    hierarchy?: ConceptRef;
    owner_person_id?: string;
    effectiveness_rating?: string;
};

export type CriticalControl = {
    control_id?: string;
    farsi_functionality?: number;
    farsi_availability?: number;
    farsi_reliability?: number;
    farsi_survivability?: number;
    /**
     * Corrected from 'interaction' — confirmed against WHSQ Guide 2021 §5/§9.2.2.1 (08-critical-control-assurance-model.md §4b)
     */
    farsi_interdependency?: number;
    readonly farsi_score?: number;
    /**
     * Guide Table 2 — 08-critical-control-assurance-model.md §4a
     */
    eia_effective?: boolean;
    eia_independent?: boolean;
    eia_auditable?: boolean;
    /**
     * Computed — 08-critical-control-assurance-model.md §6
     */
    readonly health_state?: 'Verified' | 'Healthy' | 'Degraded' | 'Overdue' | 'Unverified';
};

export type CriticalControlFarsiInput = {
    farsi_functionality?: number;
    farsi_availability?: number;
    farsi_reliability?: number;
    farsi_survivability?: number;
    farsi_interdependency?: number;
};

/**
 * 08-critical-control-assurance-model.md §4a — Guide Table 2
 */
export type ControlEiaInput = {
    eia_effective?: boolean;
    eia_independent?: boolean;
    eia_auditable?: boolean;
};

export type PerformanceStandard = PerformanceStandardInput & {
    id?: string;
};

export type PerformanceStandardInput = {
    requirement_text: string;
    measurable_criteria?: string;
};

export type VerificationActivity = VerificationActivityInput & {
    id?: string;
    /**
     * 07-inference-rules-catalogue.md R3
     */
    readonly overdue?: boolean;
};

export type VerificationActivityInput = {
    method?: ConceptRef;
    frequency?: 'Daily' | 'Weekly' | 'Fortnightly' | 'Monthly' | 'Quarterly' | 'Annual' | 'Biennial' | 'Other';
    due_date?: string;
    last_completed?: string;
    performed_by_person_id?: string;
    result?: string;
};

export type Evidence = EvidenceInput & {
    id?: string;
    uploaded_at?: string;
};

export type EvidenceInput = {
    type?: ConceptRef;
    source_document_id?: string;
    uploaded_by_person_id?: string;
    linked_entity_type?: string;
    linked_entity_id?: string;
};

export type Tarp = TarpInput & {
    id?: string;
    status?: 'active' | 'triggered' | 'resolved' | 'retired';
};

export type TarpInput = {
    trigger_condition: string;
    trigger_source_rule?: 'R3' | 'R5' | 'R6' | 'R8' | 'R9' | 'R11' | 'R12' | 'R14' | 'R16' | 'R17' | 'R18';
    required_action: string;
    response_owner_person_id?: string;
    escalation_level?: 'supervisor' | 'manager' | 'executive';
};

export type Incident = IncidentInput & {
    id?: string;
    created_at?: string;
};

export type IncidentInput = {
    datetime: string;
    incident_type?: ConceptRef;
    severity?: number;
    vrtp_severity?: 'First Aid' | 'Medical Treatment Injury' | 'Lost Time Injury' | 'Serious Injury' | 'Dangerous Incident' | 'Near Miss';
    location?: string;
    asset_id?: string;
    reporter_person_id?: string;
    description: string;
    injuries?: string;
    witnesses?: string;
    immediate_actions?: string;
    immediate_cause?: string;
    root_cause?: string;
    whsq_notified?: 'Not yet assessed' | 'Yes' | 'No - assessed not required' | 'No - under assessment';
    /**
     * Chapter 9A — see 09-regulatory-knowledge-model.md §4
     */
    osr_notified?: 'Not applicable / under assessment' | 'Yes' | 'No - assessed not required' | 'No - under assessment';
    investigation_status?: 'Not Started' | 'In Progress' | 'Complete';
    status?: 'Open' | 'Under Investigation' | 'Closed';
    /**
     * WHS Act 2011 s.35 notifiable-incident determination (death / s.36 serious injury / s.37 dangerous incident) — operator-determined, see ADR-006 §9
     */
    is_notifiable_incident?: boolean;
};

export type Investigation = InvestigationInput & {
    id?: string;
    readonly incident_id?: string;
    created_at?: string;
    updated_at?: string;
};

export type InvestigationInput = {
    /**
     * TO BE CONFIRMED — ICAM or VRTP-mandated equivalent (03-postgresql-schema.sql investigations.method; docs/knowledge-graph/README.md open item)
     */
    method?: string;
    findings?: string;
    contributing_factors?: string;
};

export type Action = ActionInput & {
    id?: string;
};

export type ActionInput = {
    source_type?: ConceptRef;
    source_id?: string;
    description: string;
    root_cause_category?: ConceptRef;
    priority?: 'Critical' | 'High' | 'Medium' | 'Low';
    assigned_to_person_id?: string;
    due_date?: string;
    status?: 'Open' | 'In Progress' | 'Closed';
    effectiveness_review?: 'Not Reviewed' | 'Effective' | 'Partially Effective' | 'Ineffective';
    completion_date?: string;
    notes?: string;
};

export type Audit = AuditInput & {
    id?: string;
};

export type AuditInput = {
    audit_type: 'Internal Audit' | 'External Audit' | 'Site Inspection' | 'Management Review' | 'Regulatory Inspection' | 'Other';
    title: string;
    scope?: string;
    planned_date?: string;
    actual_date?: string;
    auditor_person_id?: string;
    area?: string;
    status?: 'Planned' | 'In Progress' | 'Complete' | 'Cancelled';
};

export type AuditFinding = AuditFindingInput & {
    id?: string;
};

export type AuditFindingInput = {
    severity?: string;
    description: string;
};

export type SafetyCaseClaim = SafetyCaseClaimInput & {
    id?: string;
    assurance_status?: string;
};

export type SafetyCaseClaimInput = {
    hazard_id?: string;
    critical_control_id?: string;
    claim_text: string;
    evidence_ids?: Array<string>;
    requirement_ids?: Array<string>;
};

export type SafetyCaseClaimDetail = SafetyCaseClaim & {
    /**
     * 05-knowledge-provenance-model.md §4
     */
    effective_confidence?: number;
    unresolved_segments?: Array<string>;
    chain?: GraphResult;
};

export type Requirement = {
    id?: string;
    source?: ConceptRef;
    clause_ref?: string;
    text?: string;
    applies_to_entity_type?: string;
    status?: 'TO_BE_CONFIRMED' | 'confirmed';
};

export type Document = {
    id?: string;
    filename?: string;
    mime_type?: string;
    uploaded_at?: string;
    extraction_status?: 'pending' | 'processing' | 'extracted' | 'failed' | 'reviewed';
};

export type ExtractionRun = {
    id?: string;
    document_id?: string;
    status?: 'running' | 'complete' | 'failed';
    drafts?: Array<ExtractionDraft>;
};

/**
 * Matches 04-ai-extraction-specification.md §4 schema
 */
export type ExtractionDraft = {
    id?: string;
    source_span?: {
        [key: string]: unknown;
    };
    /**
     * Hazard/Risk/Controls/Verification/Evidence draft — full shape in 04-ai-extraction-specification.md §4
     */
    payload?: {
        [key: string]: unknown;
    };
    overall_confidence?: number;
    routing?: 'auto-accept' | 'flag-for-review' | 'reject';
};

export type OntologyScheme = {
    id?: string;
    name?: string;
    description?: string;
    version?: number;
};

export type Concept = ConceptInput & {
    id?: string;
    status?: 'draft' | 'reviewed' | 'approved' | 'published' | 'deprecated';
};

export type ConceptInput = {
    scheme_id: string;
    parent_concept_id?: string;
    pref_label: string;
    definition?: string;
    source_ref?: string;
};

export type ConceptAlias = ConceptAliasInput & {
    id?: string;
};

export type ConceptAliasInput = {
    alias_text: string;
    alias_type?: 'synonym' | 'abbreviation' | 'deprecated_term';
};

export type ExtractionRule = ExtractionRuleInput & {
    id?: string;
};

export type ExtractionRuleInput = {
    target_concept_id: string;
    pattern_type: 'regex' | 'embedding-similarity' | 'llm-prompt-instruction';
    confidence_threshold: number;
    action: 'auto-accept' | 'flag-for-review' | 'reject';
    example_positive?: string;
    example_negative?: string;
};

export type GapFinding = {
    rule?: 'R3' | 'R5' | 'R6' | 'R8' | 'R9' | 'R11' | 'R12' | 'R14' | 'R16' | 'R17' | 'R18';
    entity_type?: string;
    entity_id?: string;
    summary?: string;
    detected_at?: string;
};

export type GraphResult = {
    nodes?: Array<{
        id?: string;
        label?: string;
        properties?: {
            [key: string]: unknown;
        };
    }>;
    edges?: Array<{
        type?: string;
        source?: string;
        target?: string;
        properties?: {
            [key: string]: unknown;
        };
    }>;
};

export type DeviceBoundary = DeviceBoundaryInput & {
    id?: string;
};

export type DeviceBoundaryInput = {
    boundary_description: string;
    includes_description?: string;
    excludes_description?: string;
};

export type Interface = InterfaceInput & {
    id?: string;
};

export type InterfaceInput = {
    interface_type: 'external_hazard' | 'internal_hazard' | 'worker_interaction' | 'patron_interaction' | 'supporting_system' | 'utility' | 'environment';
    description: string;
};

export type CredibleEvent = CredibleEventInput & {
    id?: string;
};

export type CredibleEventInput = {
    risk_id?: string;
    description: string;
    loss_of_control_description?: string;
    is_adi?: boolean;
};

export type SafetyAssessment = SafetyAssessmentInput & {
    id?: string;
};

export type SafetyAssessmentInput = {
    device_boundary_id: string;
    scope_description: string;
    /**
     * Operator's documented interpretation — not a fixed number, see 09-regulatory-knowledge-model.md §6
     */
    serious_risk_threshold_note?: string;
    unmitigated_risk_method?: string;
    status?: string;
    prepared_by_person_id?: string;
    assessment_date?: string;
};

export type SafetyArgument = SafetyArgumentInput & {
    id?: string;
};

export type SafetyArgumentInput = {
    /**
     * The reasoning connecting evidence to the claim — GSN Strategy-equivalent
     */
    argument_text: string;
    sequence?: number;
    /**
     * Must be a subset of evidence already SUPPORTS-linked to the parent claim
     */
    evidence_ids?: Array<string>;
};

export type MonitoringSummary = {
    id?: string;
    period_start?: string;
    period_end?: string;
    verification_count?: number;
    pass_count?: number;
    trend?: 'improving' | 'stable' | 'declining';
    /**
     * 08-critical-control-assurance-model.md §5.1
     */
    indicator_class?: 'leading' | 'lagging';
    summary_text?: string;
    generated_at?: string;
};

export type Demonstration = {
    id?: string;
    demonstration_type?: 'control_adequacy' | 'hazard_to_assurance_chain' | 'moc_effectiveness' | 'governance_effectiveness' | 'verification_confidence' | 'evidence_support';
    scope_entity_type?: string;
    scope_entity_id?: string;
    generated_narrative?: string;
    /**
     * Every graph fact cited — no claim in generated_narrative may lack an entry here (11-safety-case-demonstration-model.md §7.3)
     */
    source_fact_refs?: Array<{
        [key: string]: unknown;
    }>;
    status?: 'draft' | 'reviewed' | 'approved' | 'published';
    generated_at?: string;
    /**
     * 07-inference-rules-catalogue.md R16
     */
    readonly is_stale?: boolean;
};

export type ManagementOfChange = ManagementOfChangeInput & {
    id?: string;
};

export type ManagementOfChangeInput = {
    asset_id?: string;
    change_description: string;
    /**
     * Guide's own examples: minor = sign colour change; major = roller coaster component replacement
     */
    change_type: 'minor' | 'major';
    change_category?: 'amusement_device' | 'plant_or_structure' | 'operation_or_nature_of_operation' | 'worker_safety_role' | 'training' | 'maintenance_or_inspection' | 'annual_or_major_inspection' | 'organisational';
    risk_reassessment_required?: boolean;
    linked_safety_assessment_id?: string;
    requested_by_person_id?: string;
    status?: 'proposed' | 'under_review' | 'approved' | 'implemented' | 'closed';
};

export type ReviewTrigger = ReviewTriggerInput & {
    id?: string;
};

export type ReviewTriggerInput = {
    trigger_type: 'control_not_controlling_risk' | 'new_adh_identified' | 'worker_consultation_flagged' | 'regulator_requested' | 'moc_change';
    description: string;
    requires_update_of: Array<'safety_assessment' | 'emergency_plan' | 'sms' | 'safety_case' | 'competency'>;
    status?: 'open' | 'actioned' | 'closed';
};

export type EmergencyPlan = EmergencyPlanInput & {
    id?: string;
};

export type EmergencyPlanInput = {
    /**
     * One plan per park — Guide §12.4
     */
    park_id: string;
    title: string;
    /**
     * Safety-case summary only — the full plan is not a material particular of the licence (Guide §12.4)
     */
    summary: string;
    max_persons_normal_day?: number;
    max_persons_peak_season?: number;
    /**
     * Schedule 18B 3.2, 3.4
     */
    warning_system_description?: string;
    corporate_response_plan_description?: string;
    status?: 'draft' | 'current' | 'superseded';
    effective_date?: string;
    /**
     * s.608N(4)
     */
    sent_to_regulator_at?: string;
};

export type EmergencyPlanCredibleEvent = EmergencyPlanCredibleEventInput & {
    emergency_plan_id?: string;
};

export type EmergencyPlanCredibleEventInput = {
    credible_event_id: string;
    /**
     * The specific response action(s) for this ADI within the combined plan (Guide §12)
     */
    response_summary?: string;
};

export type EmergencyExercise = EmergencyExerciseInput & {
    id?: string;
    emergency_plan_id?: string;
};

export type EmergencyExerciseInput = {
    /**
     * Nullable for desktop_exercise/corporate_response_exercise (Guide §12.1, §12.3)
     */
    credible_event_id?: string;
    exercise_type: 'drill' | 'scenario_test' | 'desktop_exercise' | 'evacuation_exercise' | 'corporate_response_exercise';
    planned_date?: string;
    conducted_date?: string;
    status?: 'planned' | 'conducted' | 'cancelled';
    learnings?: string;
    learnings_implemented?: boolean;
};

export type EmergencyServiceConsultation = EmergencyServiceConsultationInput & {
    id?: string;
    emergency_plan_id?: string;
};

export type EmergencyServiceConsultationInput = {
    /**
     * Emergency Service Organisation taxonomy — QFES/QPS/QAS/other
     */
    organisation_concept_id: string;
    consultation_date?: string;
    recommendation_text?: string;
    /**
     * Guide §12.3 — how the recommendation was incorporated
     */
    incorporation_description?: string;
    /**
     * s.608N(4)
     */
    plan_sent_at?: string;
};

export type Role = RoleInput & {
    id?: string;
};

export type RoleInput = {
    name: string;
    role_category?: 'operator' | 'technical_services' | 'supervisor' | 'management' | 'officer' | 'contractor' | 'security';
};

export type Competency = CompetencyInput & {
    id?: string;
};

export type CompetencyInput = {
    person_id: string;
    role_id?: string;
    /**
     * Operator-competency as a control-assurance input — 07-inference-rules-catalogue.md R20
     */
    critical_control_id?: string;
    /**
     * training | qualification | licence | oem_certification | authorisation | information_briefing
     */
    competency_type_concept_id?: string;
    description: string;
    /**
     * Trainer/assessor — Guide §10.8
     */
    assessed_by_person_id?: string;
    assessment_date?: string;
    /**
     * 07-inference-rules-catalogue.md R19 lapses on expiry; R21 can flag review early on a new/changed ADH
     */
    currency_expiry_date?: string;
    status?: 'current' | 'lapsed' | 'pending_assessment' | 'revoked';
};

export type RiskWritable = RiskInput & {
    id?: string;
};

export type ControlWritable = ControlInput & {
    id?: string;
};

export type CriticalControlWritable = {
    control_id?: string;
    farsi_functionality?: number;
    farsi_availability?: number;
    farsi_reliability?: number;
    farsi_survivability?: number;
    /**
     * Corrected from 'interaction' — confirmed against WHSQ Guide 2021 §5/§9.2.2.1 (08-critical-control-assurance-model.md §4b)
     */
    farsi_interdependency?: number;
    /**
     * Guide Table 2 — 08-critical-control-assurance-model.md §4a
     */
    eia_effective?: boolean;
    eia_independent?: boolean;
    eia_auditable?: boolean;
};

export type VerificationActivityWritable = VerificationActivityInput & {
    id?: string;
};

export type InvestigationWritable = InvestigationInput & {
    id?: string;
    created_at?: string;
    updated_at?: string;
};

export type DemonstrationWritable = {
    id?: string;
    demonstration_type?: 'control_adequacy' | 'hazard_to_assurance_chain' | 'moc_effectiveness' | 'governance_effectiveness' | 'verification_confidence' | 'evidence_support';
    scope_entity_type?: string;
    scope_entity_id?: string;
    generated_narrative?: string;
    /**
     * Every graph fact cited — no claim in generated_narrative may lack an entry here (11-safety-case-demonstration-model.md §7.3)
     */
    source_fact_refs?: Array<{
        [key: string]: unknown;
    }>;
    status?: 'draft' | 'reviewed' | 'approved' | 'published';
    generated_at?: string;
};

export type Id = string;

export type Limit = number;

export type Offset = number;

export type GetAssetsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        park_id?: string;
    };
    url: '/assets';
};

export type GetAssetsResponses = {
    /**
     * Paginated asset list
     */
    200: {
        items?: Array<Asset>;
        total?: number;
    };
};

export type GetAssetsResponse = GetAssetsResponses[keyof GetAssetsResponses];

export type PostAssetsData = {
    body: AssetInput;
    path?: never;
    query?: never;
    url: '/assets';
};

export type PostAssetsErrors = {
    /**
     * Request failed validation
     */
    400: Error;
};

export type PostAssetsError = PostAssetsErrors[keyof PostAssetsErrors];

export type PostAssetsResponses = {
    /**
     * Created
     */
    201: Asset;
};

export type PostAssetsResponse = PostAssetsResponses[keyof PostAssetsResponses];

export type GetAssetsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type GetAssetsByIdErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetAssetsByIdError = GetAssetsByIdErrors[keyof GetAssetsByIdErrors];

export type GetAssetsByIdResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type GetAssetsByIdResponse = GetAssetsByIdResponses[keyof GetAssetsByIdResponses];

export type PatchAssetsByIdData = {
    body?: AssetInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type PatchAssetsByIdResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type PatchAssetsByIdResponse = PatchAssetsByIdResponses[keyof PatchAssetsByIdResponses];

export type GetAssetsByIdBoundaryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}/boundary';
};

export type GetAssetsByIdBoundaryErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetAssetsByIdBoundaryError = GetAssetsByIdBoundaryErrors[keyof GetAssetsByIdBoundaryErrors];

export type GetAssetsByIdBoundaryResponses = {
    /**
     * OK
     */
    200: DeviceBoundary;
};

export type GetAssetsByIdBoundaryResponse = GetAssetsByIdBoundaryResponses[keyof GetAssetsByIdBoundaryResponses];

export type PutAssetsByIdBoundaryData = {
    body?: DeviceBoundaryInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}/boundary';
};

export type PutAssetsByIdBoundaryResponses = {
    /**
     * OK
     */
    200: DeviceBoundary;
};

export type PutAssetsByIdBoundaryResponse = PutAssetsByIdBoundaryResponses[keyof PutAssetsByIdBoundaryResponses];

export type GetAssetsByIdBoundaryInterfacesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}/boundary/interfaces';
};

export type GetAssetsByIdBoundaryInterfacesResponses = {
    /**
     * OK
     */
    200: Array<Interface>;
};

export type GetAssetsByIdBoundaryInterfacesResponse = GetAssetsByIdBoundaryInterfacesResponses[keyof GetAssetsByIdBoundaryInterfacesResponses];

export type PostAssetsByIdBoundaryInterfacesData = {
    body?: InterfaceInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}/boundary/interfaces';
};

export type PostAssetsByIdBoundaryInterfacesResponses = {
    /**
     * Created
     */
    201: Interface;
};

export type PostAssetsByIdBoundaryInterfacesResponse = PostAssetsByIdBoundaryInterfacesResponses[keyof PostAssetsByIdBoundaryInterfacesResponses];

export type GetHazardsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        asset_id?: string;
        category_concept_id?: string;
    };
    url: '/hazards';
};

export type GetHazardsResponses = {
    /**
     * Paginated hazard list
     */
    200: {
        items?: Array<Hazard>;
        total?: number;
    };
};

export type GetHazardsResponse = GetHazardsResponses[keyof GetHazardsResponses];

export type PostHazardsData = {
    body: HazardInput;
    path?: never;
    query?: never;
    url: '/hazards';
};

export type PostHazardsResponses = {
    /**
     * Created
     */
    201: Hazard;
};

export type PostHazardsResponse = PostHazardsResponses[keyof PostHazardsResponses];

export type GetHazardsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/hazards/{id}';
};

export type GetHazardsByIdErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetHazardsByIdError = GetHazardsByIdErrors[keyof GetHazardsByIdErrors];

export type GetHazardsByIdResponses = {
    /**
     * OK
     */
    200: Hazard;
};

export type GetHazardsByIdResponse = GetHazardsByIdResponses[keyof GetHazardsByIdResponses];

export type PatchHazardsByIdData = {
    body?: HazardInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/hazards/{id}';
};

export type PatchHazardsByIdResponses = {
    /**
     * OK
     */
    200: Hazard;
};

export type PatchHazardsByIdResponse = PatchHazardsByIdResponses[keyof PatchHazardsByIdResponses];

export type GetHazardsByIdDuplicateCandidatesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/hazards/{id}/duplicate-candidates';
};

export type GetHazardsByIdDuplicateCandidatesResponses = {
    /**
     * Candidate duplicates with similarity score
     */
    200: Array<{
        hazard?: Hazard;
        similarity_score?: number;
    }>;
};

export type GetHazardsByIdDuplicateCandidatesResponse = GetHazardsByIdDuplicateCandidatesResponses[keyof GetHazardsByIdDuplicateCandidatesResponses];

export type GetHazardsByIdCredibleEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/hazards/{id}/credible-events';
};

export type GetHazardsByIdCredibleEventsResponses = {
    /**
     * OK
     */
    200: Array<CredibleEvent>;
};

export type GetHazardsByIdCredibleEventsResponse = GetHazardsByIdCredibleEventsResponses[keyof GetHazardsByIdCredibleEventsResponses];

export type PostHazardsByIdCredibleEventsData = {
    body?: CredibleEventInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/hazards/{id}/credible-events';
};

export type PostHazardsByIdCredibleEventsResponses = {
    /**
     * Created
     */
    201: CredibleEvent;
};

export type PostHazardsByIdCredibleEventsResponse = PostHazardsByIdCredibleEventsResponses[keyof PostHazardsByIdCredibleEventsResponses];

export type GetSafetyAssessmentsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/safety-assessments';
};

export type GetSafetyAssessmentsResponses = {
    /**
     * OK
     */
    200: Array<SafetyAssessment>;
};

export type GetSafetyAssessmentsResponse = GetSafetyAssessmentsResponses[keyof GetSafetyAssessmentsResponses];

export type PostSafetyAssessmentsData = {
    body?: SafetyAssessmentInput;
    path?: never;
    query?: never;
    url: '/safety-assessments';
};

export type PostSafetyAssessmentsResponses = {
    /**
     * Created
     */
    201: SafetyAssessment;
};

export type PostSafetyAssessmentsResponse = PostSafetyAssessmentsResponses[keyof PostSafetyAssessmentsResponses];

export type GetSafetyAssessmentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/safety-assessments/{id}';
};

export type GetSafetyAssessmentsByIdResponses = {
    /**
     * OK
     */
    200: SafetyAssessment;
};

export type GetSafetyAssessmentsByIdResponse = GetSafetyAssessmentsByIdResponses[keyof GetSafetyAssessmentsByIdResponses];

export type PatchSafetyAssessmentsByIdData = {
    body?: SafetyAssessmentInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/safety-assessments/{id}';
};

export type PatchSafetyAssessmentsByIdResponses = {
    /**
     * OK
     */
    200: SafetyAssessment;
};

export type PatchSafetyAssessmentsByIdResponse = PatchSafetyAssessmentsByIdResponses[keyof PatchSafetyAssessmentsByIdResponses];

export type GetSafetyCaseClaimsByIdArgumentsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/safety-case-claims/{id}/arguments';
};

export type GetSafetyCaseClaimsByIdArgumentsResponses = {
    /**
     * OK
     */
    200: Array<SafetyArgument>;
};

export type GetSafetyCaseClaimsByIdArgumentsResponse = GetSafetyCaseClaimsByIdArgumentsResponses[keyof GetSafetyCaseClaimsByIdArgumentsResponses];

export type PostSafetyCaseClaimsByIdArgumentsData = {
    body?: SafetyArgumentInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/safety-case-claims/{id}/arguments';
};

export type PostSafetyCaseClaimsByIdArgumentsErrors = {
    /**
     * Cited evidence not reachable from the claim's SUPPORTS chain (06-relationship-rules-catalogue.md §5a GROUNDED_IN rule)
     */
    422: unknown;
};

export type PostSafetyCaseClaimsByIdArgumentsResponses = {
    /**
     * Created
     */
    201: SafetyArgument;
};

export type PostSafetyCaseClaimsByIdArgumentsResponse = PostSafetyCaseClaimsByIdArgumentsResponses[keyof PostSafetyCaseClaimsByIdArgumentsResponses];

export type GetCriticalControlsByIdMonitoringSummariesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        indicator_class?: 'leading' | 'lagging';
    };
    url: '/critical-controls/{id}/monitoring-summaries';
};

export type GetCriticalControlsByIdMonitoringSummariesResponses = {
    /**
     * OK
     */
    200: Array<MonitoringSummary>;
};

export type GetCriticalControlsByIdMonitoringSummariesResponse = GetCriticalControlsByIdMonitoringSummariesResponses[keyof GetCriticalControlsByIdMonitoringSummariesResponses];

export type GetDemonstrationsData = {
    body?: never;
    path?: never;
    query?: {
        scope_entity_id?: string;
        status?: 'draft' | 'reviewed' | 'approved' | 'published';
        limit?: number;
        offset?: number;
    };
    url: '/demonstrations';
};

export type GetDemonstrationsResponses = {
    /**
     * OK
     */
    200: Array<Demonstration>;
};

export type GetDemonstrationsResponse = GetDemonstrationsResponses[keyof GetDemonstrationsResponses];

export type PostDemonstrationsData = {
    body?: {
        demonstration_type: 'control_adequacy' | 'hazard_to_assurance_chain' | 'moc_effectiveness' | 'governance_effectiveness' | 'verification_confidence' | 'evidence_support';
        scope_entity_type: 'safety_assessment' | 'hazard' | 'critical_control' | 'asset';
        scope_entity_id: string;
    };
    path?: never;
    query?: never;
    url: '/demonstrations';
};

export type PostDemonstrationsResponses = {
    /**
     * Generation started
     */
    202: {
        demonstration_id?: string;
    };
};

export type PostDemonstrationsResponse = PostDemonstrationsResponses[keyof PostDemonstrationsResponses];

export type GetDemonstrationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/demonstrations/{id}';
};

export type GetDemonstrationsByIdResponses = {
    /**
     * OK
     */
    200: Demonstration;
};

export type GetDemonstrationsByIdResponse = GetDemonstrationsByIdResponses[keyof GetDemonstrationsByIdResponses];

export type PostDemonstrationsByIdReviewData = {
    body?: {
        status: 'reviewed' | 'approved' | 'published';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/demonstrations/{id}/review';
};

export type PostDemonstrationsByIdReviewResponses = {
    /**
     * OK
     */
    200: Demonstration;
};

export type PostDemonstrationsByIdReviewResponse = PostDemonstrationsByIdReviewResponses[keyof PostDemonstrationsByIdReviewResponses];

export type GetManagementOfChangeData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        status?: 'proposed' | 'under_review' | 'approved' | 'implemented' | 'closed';
    };
    url: '/management-of-change';
};

export type GetManagementOfChangeResponses = {
    /**
     * OK
     */
    200: Array<ManagementOfChange>;
};

export type GetManagementOfChangeResponse = GetManagementOfChangeResponses[keyof GetManagementOfChangeResponses];

export type PostManagementOfChangeData = {
    body?: ManagementOfChangeInput;
    path?: never;
    query?: never;
    url: '/management-of-change';
};

export type PostManagementOfChangeResponses = {
    /**
     * Created
     */
    201: ManagementOfChange;
};

export type PostManagementOfChangeResponse = PostManagementOfChangeResponses[keyof PostManagementOfChangeResponses];

export type GetManagementOfChangeByIdReviewTriggersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/management-of-change/{id}/review-triggers';
};

export type GetManagementOfChangeByIdReviewTriggersResponses = {
    /**
     * OK
     */
    200: Array<ReviewTrigger>;
};

export type GetManagementOfChangeByIdReviewTriggersResponse = GetManagementOfChangeByIdReviewTriggersResponses[keyof GetManagementOfChangeByIdReviewTriggersResponses];

export type PostManagementOfChangeByIdReviewTriggersData = {
    body?: ReviewTriggerInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/management-of-change/{id}/review-triggers';
};

export type PostManagementOfChangeByIdReviewTriggersResponses = {
    /**
     * Created
     */
    201: ReviewTrigger;
};

export type PostManagementOfChangeByIdReviewTriggersResponse = PostManagementOfChangeByIdReviewTriggersResponses[keyof PostManagementOfChangeByIdReviewTriggersResponses];

export type GetParksByParkIdEmergencyPlanData = {
    body?: never;
    path: {
        parkId: string;
    };
    query?: never;
    url: '/parks/{parkId}/emergency-plan';
};

export type GetParksByParkIdEmergencyPlanErrors = {
    /**
     * No emergency plan exists yet for this park
     */
    404: unknown;
};

export type GetParksByParkIdEmergencyPlanResponses = {
    /**
     * OK
     */
    200: EmergencyPlan;
};

export type GetParksByParkIdEmergencyPlanResponse = GetParksByParkIdEmergencyPlanResponses[keyof GetParksByParkIdEmergencyPlanResponses];

export type PutParksByParkIdEmergencyPlanData = {
    body?: EmergencyPlanInput;
    path: {
        parkId: string;
    };
    query?: never;
    url: '/parks/{parkId}/emergency-plan';
};

export type PutParksByParkIdEmergencyPlanResponses = {
    /**
     * OK
     */
    200: EmergencyPlan;
};

export type PutParksByParkIdEmergencyPlanResponse = PutParksByParkIdEmergencyPlanResponses[keyof PutParksByParkIdEmergencyPlanResponses];

export type GetEmergencyPlansByIdCredibleEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/emergency-plans/{id}/credible-events';
};

export type GetEmergencyPlansByIdCredibleEventsResponses = {
    /**
     * OK
     */
    200: Array<EmergencyPlanCredibleEvent>;
};

export type GetEmergencyPlansByIdCredibleEventsResponse = GetEmergencyPlansByIdCredibleEventsResponses[keyof GetEmergencyPlansByIdCredibleEventsResponses];

export type PostEmergencyPlansByIdCredibleEventsData = {
    body?: EmergencyPlanCredibleEventInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/emergency-plans/{id}/credible-events';
};

export type PostEmergencyPlansByIdCredibleEventsResponses = {
    /**
     * Created
     */
    201: EmergencyPlanCredibleEvent;
};

export type PostEmergencyPlansByIdCredibleEventsResponse = PostEmergencyPlansByIdCredibleEventsResponses[keyof PostEmergencyPlansByIdCredibleEventsResponses];

export type GetEmergencyPlansByIdExercisesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/emergency-plans/{id}/exercises';
};

export type GetEmergencyPlansByIdExercisesResponses = {
    /**
     * OK
     */
    200: Array<EmergencyExercise>;
};

export type GetEmergencyPlansByIdExercisesResponse = GetEmergencyPlansByIdExercisesResponses[keyof GetEmergencyPlansByIdExercisesResponses];

export type PostEmergencyPlansByIdExercisesData = {
    body?: EmergencyExerciseInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/emergency-plans/{id}/exercises';
};

export type PostEmergencyPlansByIdExercisesResponses = {
    /**
     * Created
     */
    201: EmergencyExercise;
};

export type PostEmergencyPlansByIdExercisesResponse = PostEmergencyPlansByIdExercisesResponses[keyof PostEmergencyPlansByIdExercisesResponses];

export type GetEmergencyPlansByIdConsultationsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/emergency-plans/{id}/consultations';
};

export type GetEmergencyPlansByIdConsultationsResponses = {
    /**
     * OK
     */
    200: Array<EmergencyServiceConsultation>;
};

export type GetEmergencyPlansByIdConsultationsResponse = GetEmergencyPlansByIdConsultationsResponses[keyof GetEmergencyPlansByIdConsultationsResponses];

export type PostEmergencyPlansByIdConsultationsData = {
    body?: EmergencyServiceConsultationInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/emergency-plans/{id}/consultations';
};

export type PostEmergencyPlansByIdConsultationsResponses = {
    /**
     * Created
     */
    201: EmergencyServiceConsultation;
};

export type PostEmergencyPlansByIdConsultationsResponse = PostEmergencyPlansByIdConsultationsResponses[keyof PostEmergencyPlansByIdConsultationsResponses];

export type GetRisksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        hazard_id?: string;
        current_rating?: 'Extreme' | 'High' | 'Medium' | 'Low';
    };
    url: '/risks';
};

export type GetRisksResponses = {
    /**
     * Paginated risk list
     */
    200: {
        items?: Array<Risk>;
        total?: number;
    };
};

export type GetRisksResponse = GetRisksResponses[keyof GetRisksResponses];

export type PostRisksData = {
    body: RiskInput;
    path?: never;
    query?: never;
    url: '/risks';
};

export type PostRisksResponses = {
    /**
     * Created
     */
    201: Risk;
};

export type PostRisksResponse = PostRisksResponses[keyof PostRisksResponses];

export type GetRisksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/risks/{id}';
};

export type GetRisksByIdResponses = {
    /**
     * OK
     */
    200: Risk;
};

export type GetRisksByIdResponse = GetRisksByIdResponses[keyof GetRisksByIdResponses];

export type PatchRisksByIdData = {
    body?: RiskInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/risks/{id}';
};

export type PatchRisksByIdErrors = {
    /**
     * SFARP gate rejected the justification (07-inference-rules-catalogue.md R4)
     */
    422: unknown;
};

export type PatchRisksByIdResponses = {
    /**
     * OK
     */
    200: Risk;
};

export type PatchRisksByIdResponse = PatchRisksByIdResponses[keyof PatchRisksByIdResponses];

export type GetRisksByRiskIdControlsData = {
    body?: never;
    path: {
        riskId: string;
    };
    query?: never;
    url: '/risks/{riskId}/controls';
};

export type GetRisksByRiskIdControlsResponses = {
    /**
     * OK
     */
    200: Array<Control>;
};

export type GetRisksByRiskIdControlsResponse = GetRisksByRiskIdControlsResponses[keyof GetRisksByRiskIdControlsResponses];

export type PostRisksByRiskIdControlsData = {
    body?: ControlInput;
    path: {
        riskId: string;
    };
    query?: never;
    url: '/risks/{riskId}/controls';
};

export type PostRisksByRiskIdControlsResponses = {
    /**
     * Created
     */
    201: Control;
};

export type PostRisksByRiskIdControlsResponse = PostRisksByRiskIdControlsResponses[keyof PostRisksByRiskIdControlsResponses];

export type GetControlsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/controls/{id}';
};

export type GetControlsByIdResponses = {
    /**
     * OK
     */
    200: Control;
};

export type GetControlsByIdResponse = GetControlsByIdResponses[keyof GetControlsByIdResponses];

export type PostControlsByIdGateTestData = {
    body?: {
        gate_1: boolean;
        gate_2: boolean;
        gate_3: boolean;
        /**
         * Follow-up if any gate failed
         */
        is_verification_check?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/controls/{id}/gate-test';
};

export type PostControlsByIdGateTestResponses = {
    /**
     * Resulting classification
     */
    200: {
        classification?: 'Control' | 'Support' | 'Verification';
    };
};

export type PostControlsByIdGateTestResponse = PostControlsByIdGateTestResponses[keyof PostControlsByIdGateTestResponses];

export type PostControlsByIdEiaTestData = {
    body?: ControlEiaInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/controls/{id}/eia-test';
};

export type PostControlsByIdEiaTestResponses = {
    /**
     * OK
     */
    200: Control;
};

export type PostControlsByIdEiaTestResponse = PostControlsByIdEiaTestResponses[keyof PostControlsByIdEiaTestResponses];

export type PostControlsByIdCriticalControlTestData = {
    body?: {
        is_critical: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/controls/{id}/critical-control-test';
};

export type PostControlsByIdCriticalControlTestErrors = {
    /**
     * Control is not classified 'Control' — cannot be tested for criticality
     */
    409: unknown;
};

export type PostControlsByIdCriticalControlTestResponses = {
    /**
     * CriticalControl created
     */
    201: CriticalControl;
};

export type PostControlsByIdCriticalControlTestResponse = PostControlsByIdCriticalControlTestResponses[keyof PostControlsByIdCriticalControlTestResponses];

export type GetCriticalControlsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/critical-controls/{id}';
};

export type GetCriticalControlsByIdResponses = {
    /**
     * OK
     */
    200: CriticalControl;
};

export type GetCriticalControlsByIdResponse = GetCriticalControlsByIdResponses[keyof GetCriticalControlsByIdResponses];

export type PatchCriticalControlsByIdData = {
    body?: CriticalControlFarsiInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/critical-controls/{id}';
};

export type PatchCriticalControlsByIdResponses = {
    /**
     * OK
     */
    200: CriticalControl;
};

export type PatchCriticalControlsByIdResponse = PatchCriticalControlsByIdResponses[keyof PatchCriticalControlsByIdResponses];

export type GetCriticalControlsByIdPerformanceStandardsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/critical-controls/{id}/performance-standards';
};

export type GetCriticalControlsByIdPerformanceStandardsResponses = {
    /**
     * OK
     */
    200: Array<PerformanceStandard>;
};

export type GetCriticalControlsByIdPerformanceStandardsResponse = GetCriticalControlsByIdPerformanceStandardsResponses[keyof GetCriticalControlsByIdPerformanceStandardsResponses];

export type PostCriticalControlsByIdPerformanceStandardsData = {
    body?: PerformanceStandardInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/critical-controls/{id}/performance-standards';
};

export type PostCriticalControlsByIdPerformanceStandardsResponses = {
    /**
     * Created
     */
    201: PerformanceStandard;
};

export type PostCriticalControlsByIdPerformanceStandardsResponse = PostCriticalControlsByIdPerformanceStandardsResponses[keyof PostCriticalControlsByIdPerformanceStandardsResponses];

export type GetPerformanceStandardsByIdVerificationActivitiesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/performance-standards/{id}/verification-activities';
};

export type GetPerformanceStandardsByIdVerificationActivitiesResponses = {
    /**
     * OK
     */
    200: Array<VerificationActivity>;
};

export type GetPerformanceStandardsByIdVerificationActivitiesResponse = GetPerformanceStandardsByIdVerificationActivitiesResponses[keyof GetPerformanceStandardsByIdVerificationActivitiesResponses];

export type PostPerformanceStandardsByIdVerificationActivitiesData = {
    body?: VerificationActivityInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/performance-standards/{id}/verification-activities';
};

export type PostPerformanceStandardsByIdVerificationActivitiesResponses = {
    /**
     * Created
     */
    201: VerificationActivity;
};

export type PostPerformanceStandardsByIdVerificationActivitiesResponse = PostPerformanceStandardsByIdVerificationActivitiesResponses[keyof PostPerformanceStandardsByIdVerificationActivitiesResponses];

export type GetVerificationActivitiesByIdEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/verification-activities/{id}/evidence';
};

export type GetVerificationActivitiesByIdEvidenceResponses = {
    /**
     * OK
     */
    200: Array<Evidence>;
};

export type GetVerificationActivitiesByIdEvidenceResponse = GetVerificationActivitiesByIdEvidenceResponses[keyof GetVerificationActivitiesByIdEvidenceResponses];

export type PostVerificationActivitiesByIdEvidenceData = {
    body?: EvidenceInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/verification-activities/{id}/evidence';
};

export type PostVerificationActivitiesByIdEvidenceResponses = {
    /**
     * Created
     */
    201: Evidence;
};

export type PostVerificationActivitiesByIdEvidenceResponse = PostVerificationActivitiesByIdEvidenceResponses[keyof PostVerificationActivitiesByIdEvidenceResponses];

export type GetCriticalControlsByIdTarpsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/critical-controls/{id}/tarps';
};

export type GetCriticalControlsByIdTarpsResponses = {
    /**
     * OK
     */
    200: Array<Tarp>;
};

export type GetCriticalControlsByIdTarpsResponse = GetCriticalControlsByIdTarpsResponses[keyof GetCriticalControlsByIdTarpsResponses];

export type PostCriticalControlsByIdTarpsData = {
    body?: TarpInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/critical-controls/{id}/tarps';
};

export type PostCriticalControlsByIdTarpsResponses = {
    /**
     * Created
     */
    201: Tarp;
};

export type PostCriticalControlsByIdTarpsResponse = PostCriticalControlsByIdTarpsResponses[keyof PostCriticalControlsByIdTarpsResponses];

export type PostTarpsByIdResolveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tarps/{id}/resolve';
};

export type PostTarpsByIdResolveResponses = {
    /**
     * OK
     */
    200: Tarp;
};

export type PostTarpsByIdResolveResponse = PostTarpsByIdResolveResponses[keyof PostTarpsByIdResolveResponses];

export type GetIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/incidents';
};

export type GetIncidentsResponses = {
    /**
     * OK
     */
    200: {
        items?: Array<Incident>;
        total?: number;
    };
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type PostIncidentsData = {
    body?: IncidentInput;
    path?: never;
    query?: never;
    url: '/incidents';
};

export type PostIncidentsResponses = {
    /**
     * Created
     */
    201: Incident;
};

export type PostIncidentsResponse = PostIncidentsResponses[keyof PostIncidentsResponses];

export type GetIncidentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}';
};

export type GetIncidentsByIdResponses = {
    /**
     * OK
     */
    200: Incident;
};

export type GetIncidentsByIdResponse = GetIncidentsByIdResponses[keyof GetIncidentsByIdResponses];

export type PatchIncidentsByIdData = {
    body?: IncidentInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}';
};

export type PatchIncidentsByIdResponses = {
    /**
     * OK
     */
    200: Incident;
};

export type PatchIncidentsByIdResponse = PatchIncidentsByIdResponses[keyof PatchIncidentsByIdResponses];

export type PostIncidentsByIdRunInvestigationPipelineData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/run-investigation-pipeline';
};

export type PostIncidentsByIdRunInvestigationPipelineResponses = {
    /**
     * Pipeline started
     */
    202: {
        extraction_run_id?: string;
    };
};

export type PostIncidentsByIdRunInvestigationPipelineResponse = PostIncidentsByIdRunInvestigationPipelineResponses[keyof PostIncidentsByIdRunInvestigationPipelineResponses];

export type GetIncidentsByIdInvestigationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/investigation';
};

export type GetIncidentsByIdInvestigationErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetIncidentsByIdInvestigationError = GetIncidentsByIdInvestigationErrors[keyof GetIncidentsByIdInvestigationErrors];

export type GetIncidentsByIdInvestigationResponses = {
    /**
     * OK
     */
    200: Investigation;
};

export type GetIncidentsByIdInvestigationResponse = GetIncidentsByIdInvestigationResponses[keyof GetIncidentsByIdInvestigationResponses];

export type PatchIncidentsByIdInvestigationData = {
    body?: InvestigationInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/investigation';
};

export type PatchIncidentsByIdInvestigationErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type PatchIncidentsByIdInvestigationError = PatchIncidentsByIdInvestigationErrors[keyof PatchIncidentsByIdInvestigationErrors];

export type PatchIncidentsByIdInvestigationResponses = {
    /**
     * OK
     */
    200: Investigation;
};

export type PatchIncidentsByIdInvestigationResponse = PatchIncidentsByIdInvestigationResponses[keyof PatchIncidentsByIdInvestigationResponses];

export type PostIncidentsByIdInvestigationData = {
    body?: InvestigationInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/investigation';
};

export type PostIncidentsByIdInvestigationErrors = {
    /**
     * Investigation already exists for this incident (investigations.incident_id UNIQUE)
     */
    409: unknown;
};

export type PostIncidentsByIdInvestigationResponses = {
    /**
     * Created
     */
    201: Investigation;
};

export type PostIncidentsByIdInvestigationResponse = PostIncidentsByIdInvestigationResponses[keyof PostIncidentsByIdInvestigationResponses];

export type GetIncidentsByIdHazardsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/hazards';
};

export type GetIncidentsByIdHazardsResponses = {
    /**
     * OK
     */
    200: Array<Hazard>;
};

export type GetIncidentsByIdHazardsResponse = GetIncidentsByIdHazardsResponses[keyof GetIncidentsByIdHazardsResponses];

export type PostIncidentsByIdHazardsData = {
    body?: {
        hazard_id: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/hazards';
};

export type PostIncidentsByIdHazardsErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type PostIncidentsByIdHazardsError = PostIncidentsByIdHazardsErrors[keyof PostIncidentsByIdHazardsErrors];

export type PostIncidentsByIdHazardsResponses = {
    /**
     * Linked
     */
    201: unknown;
};

export type DeleteIncidentsByIdHazardsByHazardIdData = {
    body?: never;
    path: {
        id: string;
        hazardId: string;
    };
    query?: never;
    url: '/incidents/{id}/hazards/{hazardId}';
};

export type DeleteIncidentsByIdHazardsByHazardIdErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteIncidentsByIdHazardsByHazardIdError = DeleteIncidentsByIdHazardsByHazardIdErrors[keyof DeleteIncidentsByIdHazardsByHazardIdErrors];

export type DeleteIncidentsByIdHazardsByHazardIdResponses = {
    /**
     * Unlinked
     */
    204: void;
};

export type DeleteIncidentsByIdHazardsByHazardIdResponse = DeleteIncidentsByIdHazardsByHazardIdResponses[keyof DeleteIncidentsByIdHazardsByHazardIdResponses];

export type GetIncidentsByIdEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/evidence';
};

export type GetIncidentsByIdEvidenceResponses = {
    /**
     * OK
     */
    200: Array<Evidence>;
};

export type GetIncidentsByIdEvidenceResponse = GetIncidentsByIdEvidenceResponses[keyof GetIncidentsByIdEvidenceResponses];

export type PostIncidentsByIdEvidenceData = {
    body?: EvidenceInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/evidence';
};

export type PostIncidentsByIdEvidenceResponses = {
    /**
     * Created
     */
    201: Evidence;
};

export type PostIncidentsByIdEvidenceResponse = PostIncidentsByIdEvidenceResponses[keyof PostIncidentsByIdEvidenceResponses];

export type GetIncidentsByIdActionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/actions';
};

export type GetIncidentsByIdActionsResponses = {
    /**
     * OK
     */
    200: Array<Action>;
};

export type GetIncidentsByIdActionsResponse = GetIncidentsByIdActionsResponses[keyof GetIncidentsByIdActionsResponses];

export type PostIncidentsByIdActionsData = {
    body?: {
        action_id: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/actions';
};

export type PostIncidentsByIdActionsErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type PostIncidentsByIdActionsError = PostIncidentsByIdActionsErrors[keyof PostIncidentsByIdActionsErrors];

export type PostIncidentsByIdActionsResponses = {
    /**
     * Linked
     */
    201: unknown;
};

export type DeleteIncidentsByIdActionsByActionIdData = {
    body?: never;
    path: {
        id: string;
        actionId: string;
    };
    query?: never;
    url: '/incidents/{id}/actions/{actionId}';
};

export type DeleteIncidentsByIdActionsByActionIdErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type DeleteIncidentsByIdActionsByActionIdError = DeleteIncidentsByIdActionsByActionIdErrors[keyof DeleteIncidentsByIdActionsByActionIdErrors];

export type DeleteIncidentsByIdActionsByActionIdResponses = {
    /**
     * Unlinked
     */
    204: void;
};

export type DeleteIncidentsByIdActionsByActionIdResponse = DeleteIncidentsByIdActionsByActionIdResponses[keyof DeleteIncidentsByIdActionsByActionIdResponses];

export type GetActionsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        status?: 'Open' | 'In Progress' | 'Closed';
    };
    url: '/actions';
};

export type GetActionsResponses = {
    /**
     * OK
     */
    200: Array<Action>;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type PostActionsData = {
    body?: ActionInput;
    path?: never;
    query?: never;
    url: '/actions';
};

export type PostActionsResponses = {
    /**
     * Created
     */
    201: Action;
};

export type PostActionsResponse = PostActionsResponses[keyof PostActionsResponses];

export type PatchActionsByIdData = {
    body?: ActionInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/actions/{id}';
};

export type PatchActionsByIdResponses = {
    /**
     * OK
     */
    200: Action;
};

export type PatchActionsByIdResponse = PatchActionsByIdResponses[keyof PatchActionsByIdResponses];

export type GetAuditsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/audits';
};

export type GetAuditsResponses = {
    /**
     * OK
     */
    200: Array<Audit>;
};

export type GetAuditsResponse = GetAuditsResponses[keyof GetAuditsResponses];

export type PostAuditsData = {
    body?: AuditInput;
    path?: never;
    query?: never;
    url: '/audits';
};

export type PostAuditsResponses = {
    /**
     * Created
     */
    201: Audit;
};

export type PostAuditsResponse = PostAuditsResponses[keyof PostAuditsResponses];

export type GetAuditsByIdFindingsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/audits/{id}/findings';
};

export type GetAuditsByIdFindingsResponses = {
    /**
     * OK
     */
    200: Array<AuditFinding>;
};

export type GetAuditsByIdFindingsResponse = GetAuditsByIdFindingsResponses[keyof GetAuditsByIdFindingsResponses];

export type PostAuditsByIdFindingsData = {
    body?: AuditFindingInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/audits/{id}/findings';
};

export type PostAuditsByIdFindingsResponses = {
    /**
     * Created
     */
    201: AuditFinding;
};

export type PostAuditsByIdFindingsResponse = PostAuditsByIdFindingsResponses[keyof PostAuditsByIdFindingsResponses];

export type GetSafetyCaseClaimsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/safety-case-claims';
};

export type GetSafetyCaseClaimsResponses = {
    /**
     * OK
     */
    200: Array<SafetyCaseClaim>;
};

export type GetSafetyCaseClaimsResponse = GetSafetyCaseClaimsResponses[keyof GetSafetyCaseClaimsResponses];

export type PostSafetyCaseClaimsData = {
    body?: SafetyCaseClaimInput;
    path?: never;
    query?: never;
    url: '/safety-case-claims';
};

export type PostSafetyCaseClaimsErrors = {
    /**
     * Chain consistency violation (06-relationship-rules-catalogue.md §3 SUPPORTS rule) — cited evidence does not trace to the claimed hazard/critical control
     */
    422: unknown;
};

export type PostSafetyCaseClaimsResponses = {
    /**
     * Created
     */
    201: SafetyCaseClaim;
};

export type PostSafetyCaseClaimsResponse = PostSafetyCaseClaimsResponses[keyof PostSafetyCaseClaimsResponses];

export type GetSafetyCaseClaimsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/safety-case-claims/{id}';
};

export type GetSafetyCaseClaimsByIdResponses = {
    /**
     * OK
     */
    200: SafetyCaseClaimDetail;
};

export type GetSafetyCaseClaimsByIdResponse = GetSafetyCaseClaimsByIdResponses[keyof GetSafetyCaseClaimsByIdResponses];

export type GetRequirementsData = {
    body?: never;
    path?: never;
    query?: {
        source_concept_id?: string;
        status?: 'TO_BE_CONFIRMED' | 'confirmed';
    };
    url: '/requirements';
};

export type GetRequirementsResponses = {
    /**
     * OK
     */
    200: Array<Requirement>;
};

export type GetRequirementsResponse = GetRequirementsResponses[keyof GetRequirementsResponses];

export type GetRequirementsByIdCoverageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/requirements/{id}/coverage';
};

export type GetRequirementsByIdCoverageResponses = {
    /**
     * OK
     */
    200: Array<SafetyCaseClaim>;
};

export type GetRequirementsByIdCoverageResponse = GetRequirementsByIdCoverageResponses[keyof GetRequirementsByIdCoverageResponses];

export type PostDocumentsData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/documents';
};

export type PostDocumentsResponses = {
    /**
     * Uploaded
     */
    201: Document;
};

export type PostDocumentsResponse = PostDocumentsResponses[keyof PostDocumentsResponses];

export type GetDocumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type GetDocumentsByIdResponses = {
    /**
     * OK
     */
    200: Document;
};

export type GetDocumentsByIdResponse = GetDocumentsByIdResponses[keyof GetDocumentsByIdResponses];

export type PostDocumentsByIdExtractData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}/extract';
};

export type PostDocumentsByIdExtractResponses = {
    /**
     * Started
     */
    202: {
        extraction_run_id?: string;
    };
};

export type PostDocumentsByIdExtractResponse = PostDocumentsByIdExtractResponses[keyof PostDocumentsByIdExtractResponses];

export type GetExtractionRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/extraction-runs/{id}';
};

export type GetExtractionRunsByIdResponses = {
    /**
     * OK
     */
    200: ExtractionRun;
};

export type GetExtractionRunsByIdResponse = GetExtractionRunsByIdResponses[keyof GetExtractionRunsByIdResponses];

export type PostExtractionRunsByIdDraftsByDraftIdApproveData = {
    body?: {
        /**
         * Optional field edits applied before commit
         */
        edits?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
        draftId: string;
    };
    query?: never;
    url: '/extraction-runs/{id}/drafts/{draftId}/approve';
};

export type PostExtractionRunsByIdDraftsByDraftIdApproveResponses = {
    /**
     * Committed
     */
    200: {
        entity_type?: string;
        entity_id?: string;
    };
};

export type PostExtractionRunsByIdDraftsByDraftIdApproveResponse = PostExtractionRunsByIdDraftsByDraftIdApproveResponses[keyof PostExtractionRunsByIdDraftsByDraftIdApproveResponses];

export type PostExtractionRunsByIdDraftsByDraftIdRejectData = {
    body?: {
        reason?: string;
    };
    path: {
        id: string;
        draftId: string;
    };
    query?: never;
    url: '/extraction-runs/{id}/drafts/{draftId}/reject';
};

export type PostExtractionRunsByIdDraftsByDraftIdRejectResponses = {
    /**
     * Rejected
     */
    200: unknown;
};

export type GetOntologySchemesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ontology/schemes';
};

export type GetOntologySchemesResponses = {
    /**
     * OK
     */
    200: Array<OntologyScheme>;
};

export type GetOntologySchemesResponse = GetOntologySchemesResponses[keyof GetOntologySchemesResponses];

export type GetOntologyConceptsData = {
    body?: never;
    path?: never;
    query?: {
        scheme_id?: string;
        /**
         * Search pref_label + aliases
         */
        q?: string;
        status?: 'draft' | 'reviewed' | 'approved' | 'published' | 'deprecated';
    };
    url: '/ontology/concepts';
};

export type GetOntologyConceptsResponses = {
    /**
     * OK
     */
    200: Array<Concept>;
};

export type GetOntologyConceptsResponse = GetOntologyConceptsResponses[keyof GetOntologyConceptsResponses];

export type PostOntologyConceptsData = {
    body?: ConceptInput;
    path?: never;
    query?: never;
    url: '/ontology/concepts';
};

export type PostOntologyConceptsResponses = {
    /**
     * Created as draft
     */
    201: Concept;
};

export type PostOntologyConceptsResponse = PostOntologyConceptsResponses[keyof PostOntologyConceptsResponses];

export type PostOntologyConceptsByIdPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/ontology/concepts/{id}/publish';
};

export type PostOntologyConceptsByIdPublishResponses = {
    /**
     * OK
     */
    200: Concept;
};

export type PostOntologyConceptsByIdPublishResponse = PostOntologyConceptsByIdPublishResponses[keyof PostOntologyConceptsByIdPublishResponses];

export type PostOntologyConceptsByIdAliasesData = {
    body?: ConceptAliasInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/ontology/concepts/{id}/aliases';
};

export type PostOntologyConceptsByIdAliasesResponses = {
    /**
     * Created
     */
    201: ConceptAlias;
};

export type PostOntologyConceptsByIdAliasesResponse = PostOntologyConceptsByIdAliasesResponses[keyof PostOntologyConceptsByIdAliasesResponses];

export type GetOntologyExtractionRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ontology/extraction-rules';
};

export type GetOntologyExtractionRulesResponses = {
    /**
     * OK
     */
    200: Array<ExtractionRule>;
};

export type GetOntologyExtractionRulesResponse = GetOntologyExtractionRulesResponses[keyof GetOntologyExtractionRulesResponses];

export type PostOntologyExtractionRulesData = {
    body?: ExtractionRuleInput;
    path?: never;
    query?: never;
    url: '/ontology/extraction-rules';
};

export type PostOntologyExtractionRulesResponses = {
    /**
     * Created
     */
    201: ExtractionRule;
};

export type PostOntologyExtractionRulesResponse = PostOntologyExtractionRulesResponses[keyof PostOntologyExtractionRulesResponses];

export type PostGraphQueryByPatternIdData = {
    /**
     * Pattern-specific parameters, e.g. an asset_id value for Q2
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Named query patterns only (01-enterprise-knowledge-graph-specification.md §5) — no arbitrary Cypher accepted from clients
         */
        patternId: 'Q1_critical_risk_assurance' | 'Q2_controls_by_hazard_type' | 'Q3_overdue_critical_controls' | 'Q4_duplicate_hazards' | 'Q5_safety_case_traceability' | 'Q6_incident_impact' | 'Q7_regulatory_coverage_gaps';
    };
    query?: never;
    url: '/graph/query/{patternId}';
};

export type PostGraphQueryByPatternIdResponses = {
    /**
     * Graph result (nodes + edges, Cytoscape-ready)
     */
    200: GraphResult;
};

export type PostGraphQueryByPatternIdResponse = PostGraphQueryByPatternIdResponses[keyof PostGraphQueryByPatternIdResponses];

export type GetGapAnalysisFindingsData = {
    body?: never;
    path?: never;
    query?: {
        rule?: 'R3' | 'R5' | 'R6' | 'R8' | 'R9' | 'R11' | 'R12' | 'R14' | 'R16' | 'R17' | 'R18';
        limit?: number;
        offset?: number;
    };
    url: '/gap-analysis/findings';
};

export type GetGapAnalysisFindingsResponses = {
    /**
     * OK
     */
    200: Array<GapFinding>;
};

export type GetGapAnalysisFindingsResponse = GetGapAnalysisFindingsResponses[keyof GetGapAnalysisFindingsResponses];

export type GetPersonsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/persons';
};

export type GetPersonsResponses = {
    /**
     * OK
     */
    200: Array<Person>;
};

export type GetPersonsResponse = GetPersonsResponses[keyof GetPersonsResponses];

export type PostPersonsData = {
    body?: PersonInput;
    path?: never;
    query?: never;
    url: '/persons';
};

export type PostPersonsResponses = {
    /**
     * Created
     */
    201: Person;
};

export type PostPersonsResponse = PostPersonsResponses[keyof PostPersonsResponses];

export type GetParksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parks';
};

export type GetParksResponses = {
    /**
     * OK
     */
    200: Array<Park>;
};

export type GetParksResponse = GetParksResponses[keyof GetParksResponses];

export type GetRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roles';
};

export type GetRolesResponses = {
    /**
     * OK
     */
    200: Array<Role>;
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type PostRolesData = {
    body?: RoleInput;
    path?: never;
    query?: never;
    url: '/roles';
};

export type PostRolesResponses = {
    /**
     * Created
     */
    201: Role;
};

export type PostRolesResponse = PostRolesResponses[keyof PostRolesResponses];

export type GetCompetenciesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        person_id?: string;
        status?: 'current' | 'lapsed' | 'pending_assessment' | 'revoked';
    };
    url: '/competencies';
};

export type GetCompetenciesResponses = {
    /**
     * OK
     */
    200: Array<Competency>;
};

export type GetCompetenciesResponse = GetCompetenciesResponses[keyof GetCompetenciesResponses];

export type PostCompetenciesData = {
    body?: CompetencyInput;
    path?: never;
    query?: never;
    url: '/competencies';
};

export type PostCompetenciesResponses = {
    /**
     * Created
     */
    201: Competency;
};

export type PostCompetenciesResponse = PostCompetenciesResponses[keyof PostCompetenciesResponses];

export type GetCompetenciesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/competencies/{id}';
};

export type GetCompetenciesByIdResponses = {
    /**
     * OK
     */
    200: Competency;
};

export type GetCompetenciesByIdResponse = GetCompetenciesByIdResponses[keyof GetCompetenciesByIdResponses];

export type PatchCompetenciesByIdData = {
    body?: CompetencyInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/competencies/{id}';
};

export type PatchCompetenciesByIdResponses = {
    /**
     * OK
     */
    200: Competency;
};

export type PatchCompetenciesByIdResponse = PatchCompetenciesByIdResponses[keyof PatchCompetenciesByIdResponses];

export type GetCompetenciesByIdEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/competencies/{id}/evidence';
};

export type GetCompetenciesByIdEvidenceResponses = {
    /**
     * OK
     */
    200: Array<Evidence>;
};

export type GetCompetenciesByIdEvidenceResponse = GetCompetenciesByIdEvidenceResponses[keyof GetCompetenciesByIdEvidenceResponses];

export type PostCompetenciesByIdEvidenceData = {
    body?: {
        evidence_id: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/competencies/{id}/evidence';
};

export type PostCompetenciesByIdEvidenceResponses = {
    /**
     * Created
     */
    201: unknown;
};
